# Generated by Django 6.0.7 on 2026-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='GST/VAT/Tax ID', max_length=100, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('credit_terms', models.IntegerField(default=0, help_text='Net payment terms in days, e.g., 30')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
