# Generated by Django 6.0.7 on 2026-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_zero_amount_journal_lines'),
        ('contacts', '0002_historicalcontact'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='journalline_amount_positive'),
        ),
    ]
