# Generated by Django 6.0.7 on 2026-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GST 18%, VAT 15%', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
