# Generated by Django 6.0.7 on 2026-07-11 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_historicalcontact'),
        ('invoices', '0004_seed_invoice_number_sequence'),
        ('items', '0002_historicalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Supports fractional quantities, e.g. hours worked', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_in_due_dat_6cc0ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoicelineitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoicelineitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='invoicelineitem_discount_non_negative'),
        ),
    ]
